Console.WriteLine("ВВЕДИТЕ ВАШЕ ИМЯ");
string name = Console.ReadLine();
Console.Write("ЗДРАВСТВУЙТЕ, ");
Console.Write(name);
Console.WriteLine(", ВВЕДИТЕ ПЕРВОЕ ЧИСЛО");
double first = Console.Read();
Console.WriteLine("ВВЕДИТЕ ВТОРОЕ ЧИСЛО");
double second = Console.Read();
double result = first + second;
Console.Write(result);
